services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Migrations\:
        resource: '../migrations/'

    App\DataFixtures\:
        resource: '../DataFixtures/'
