services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Migrations\:
        resource: '../migrations/'

    security.role_hierarchy:
        class: 'App\Security\RoleHierarchy'
        arguments:
          $hierarchy: '%security.role_hierarchy.roles%'

    Symfony\Component\Security\Core\Role\RoleHierarchyInterface: '@security.role_hierarchy'
