<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20230422152520 extends AbstractMigration
{
    public function getDescription(): string
    {
        return "Create city information table and populate it";
    }

    public function up(Schema $schema): void
    {
        $this->addSql('
            CREATE TABLE city (
                id INT AUTO_INCREMENT NOT NULL,
                name VARCHAR(50) NOT NULL,
                PRIMARY KEY(id)
            ) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
        ');
        $this->addSql('
            INSERT INTO city (name) VALUES 
            (\'Warsaw\'),
            (\'Kraków\'),
            (\'Łódź\'),
            (\'Wrocław\'),
            (\'Poznań\'),
            (\'Gdańsk\'),
            (\'Szczecin\'),
            (\'Bydgoszcz\'),
            (\'Lublin\'),
            (\'Białystok\'),
            (\'Katowice\'),
            (\'Gdynia\'),
            (\'Częstochowa\'),
            (\'Radom\'),
            (\'Toruń\'),
            (\'Sosnowiec\'),
            (\'Kielce\'),
            (\'Rzeszów\'),
            (\'Gliwice\'),
            (\'Zabrze\'),
            (\'Olsztyn\'),
            (\'Bielsko-Biała\'),
            (\'Bytom\'),
            (\'Rybnik\'),
            (\'Ruda Śląska\'),
            (\'Zielona Góra\'),
            (\'Tychy\'),
            (\'Opole\'),
            (\'Gorzów Wielkopolski\'),
            (\'Dąbrowa Górnicza\'),
            (\'Płock\'),
            (\'Elbląg\'),
            (\'Wałbrzych\'),
            (\'Chorzów\'),
            (\'Tarnów\'),
            (\'Koszalin\'),
            (\'Kalisz\'),
            (\'Legnica\'),
            (\'Włocławek\'),
            (\'Grudziądz\'),
            (\'Jaworzno\'),
            (\'Jelenia Góra\'),
            (\'Siedlce\'),
            (\'Mysłowice\'),
            (\'Piotrków Trybunalski\'),
            (\'Konin\'),
            (\'Inowrocław\'),
            (\'Ostrowiec Świętokrzyski\'),
            (\'Suwałki\'),
            (\'Gniezno\'),
            (\'Przemyśl\'),
            (\'Głogów\'),
            (\'Zamość\'),
            (\'Pabianice\'),
            (\'Leszno\'),
            (\'Łomża\'),
            (\'Ełk\'),
            (\'Tarnowskie Góry\'),
            (\'Chełm\'),
            (\'Pruszków\'),
            (\'Mielec\'),
            (\'Bełchatów\'),
            (\'Świdnica\'),
            (\'Biała Podlaska\'),
            (\'Będzin\'),
            (\'Legionowo\'),
            (\'Ostrołęka\'),
            (\'Puławy\'),
            (\'Starogard Gdański\'),
            (\'Skierniewice\'),
            (\'Tarnobrzeg\'),
            (\'Starachowice\'),
            (\'Kutno\'),
            (\'Rumia\'),
            (\'Nysa\'),
            (\'Kołobrzeg\'),
            (\'Dębica\'),
            (\'Ciechanów\'),
            (\'Świdnik\'),
            (\'Otwock\'),
            (\'Sieradz\'),
            (\'Mikołów\'),
            (\'Świnoujście\'),
            (\'Kwidzyn\'),
            (\'Chojnice\'),
            (\'Nowa Sól\'),
            (\'Bolesławiec\'),
            (\'Oświęcim\'),
            (\'Malbork\'),
            (\'Żary\'),
            (\'Jarosław\'),
            (\'Sopot\'),
            (\'Chrzanów\'),
            (\'Brzeg\'),
            (\'Jasło\'),
            (\'Lębork\'),
            (\'Cieszyn\'),
            (\'Czeladź\'),
            (\'Kraśnik\'),
            (\'Nowy Targ\'),
            (\'Iława\'),
            (\'Police\'),
            (\'Dzierżoniów\'),
            (\'Grodzisk Mazowiecki\'),
            (\'Zgorzelec\'),
            (\'Łowicz\'),
            (\'Łuków\'),
            (\'Bielsk Podlaski\'),
            (\'Bielawa\'),
            (\'Augustów\'),
            (\'Bochnia\'),
            (\'Mława\'),
            (\'Giżycko\'),
            (\'Brodnica\'),
            (\'Krotoszyn\'),
            (\'Kętrzyn\'),
            (\'Zakopane\'),
            (\'Gorlice\'),
            (\'Biłgoraj\'),
            (\'Kłodzko\'),
            (\'Luboń\'),
            (\'Brzozów\'),
            (\'Wałcz\'),
            (\'Kluczbork\'),
            (\'Jarocin\'),
            (\'Świecie\'),
            (\'Wągrowiec\'),
            (\'Skawina\'),
            (\'Sandomierz\'),
            (\'Białogard\'),
            (\'Kościan\'),
            (\'Kościerzyna\'),
            (\'Szczytno\'),
            (\'Ostrów Mazowiecka\'),
            (\'Jawor\'),
            (\'Goleniów\'),
            (\'Lubartów\'),
            (\'Świedbodzin\'),
            (\'Grajewo\'),
            (\'Wieliczka\'),
            (\'Łęczna\'),
            (\'Opoczno\'),
            (\'Koło\'),
            (\'Działdowo\'),
            (\'Prudnik\'),
            (\'Gryfino\'),
            (\'Hajnówka\'),
            (\'Chełmno\'),
            (\'Pleszew\'),
            (\'Gostyń\'),
            (\'Nakło nad Notecią\'),
            (\'Pułtusk\'),
            (\'Chodzież\'),
            (\'Krasnystaw\'),
            (\'Gostynin\'),
            (\'Międzyrzecz\'),
            (\'Łask\'),
            (\'Oborniki\'),
            (\'Rawa Mazowiecka\'),
            (\'Łańcut\'),
            (\'Garwolin\'),
            (\'Kozienice\'),
            (\'Braniewo\'),
            (\'Bytów\'),
            (\'Brzesko\'),
            (\'Grójec\'),
            (\'Krapkowice\'),
            (\'Rypin\'),
            (\'Gryfice\'),
            (\'Olecko\'),
            (\'Złotoryja\'),
            (\'Przeworsk\'),
            (\'Łęczyca\'),
            (\'Jędrzejów\'),
            (\'Siemiatycze\'),
            (\'Choszczno\'),
            (\'Limanowa\'),
            (\'Grodzisk Wielkopolski\'),
            (\'Wschowa\'),
            (\'Nidzica\'),
            (\'Człuchów\'),
            (\'Gołdap\'),
            (\'Głubczyce\'),
            (\'Wolsztyn\'),
            (\'Trzebnica\'),
            (\'Włodawa\'),
            (\'Golub-Dobrzyń\'),
            (\'Brzeziny\'),
            (\'Lubaczów\'),
            (\'Aleksandrów Kujawski\'),
            (\'Węgorzewo\'),
            (\'Janów Lubelski\'),
            (\'Góra\'),
            (\'Drawsko Pomorskie\'),
            (\'Krosno Odrzańskie\'),
            (\'Nowe Miasto Lubawskie\'),
            (\'Kolno\'),
            (\'Lwówek Śląski\'),
            (\'Kamień Pomorski\'),
            (\'Kolbuszowa\'),
            (\'Kazimierza Wielka\'),
            (\'Hrubieszów\'),
            (\'Świętochłowice\'),
            (\'Lubin\'),
            (\'Mińsk Mazowiecki\'),
            (\'Żyrardów\'),
            (\'Tczew\'),
            (\'Ostróda\'),
            (\'Siemianowice Śląskie\'),
            (\'Puck\'),
            (\'Wejherowo\'),
            (\'Sokołów Podlaski\'),
            (\'Płońsk\'),
            (\'Wąbrzeźno\'),
            (\'Mrągowo\'),
            (\'Pruszcz Gdański\'),
            (\'Zduńska Wola\'),
            (\'Oleśnica\'),
            (\'Ostrów Wielkopolski\'),
            (\'Turek\'),
            (\'Złotów\'),
            (\'Tomaszów Mazowiecki\'),
            (\'Tomaszów Lubelski\'),
            (\'Nowy Sącz\'),
            (\'Sochaczew\'),
            (\'Piekary Śląskie\'),
            (\'Stargard Szczeciński\'),
            (\'Lipno\'),
            (\'Zgierz\'),
            (\'Lubań\'),
            (\'Nowy Dwór Mazowiecki\'),
            (\'Zambrów\'),
            (\'Szczecinek\'),
            (\'Sejny\'),
            (\'Oława\'),
            (\'Czarnków\'),
            (\'Lidzbark Warmiński\'),
            (\'Kamienna Góra\'),
            (\'Słupca\'),
            (\'Jastrzębie-Zdrój\'),
            (\'Krosno\'),
            (\'Skarżysko-Kamienna\'),
            (\'Sanok\'),
            (\'Radziejów\'),
            (\'Bartoszyce\'),
            (\'Maków Mazowiecki\'),
            (\'Sierpc\'),
            (\'Wodzisław Śląski\'),
            (\'Żory\'),
            (\'Radomsko\'),
            (\'Wołomin\'),
            (\'Radzyń Podlaski\'),
            (\'Sławno\'),
            (\'Stalowa Wola\'),
            (\'Racibórz\'),
            (\'Piła\'),
            (\'Żywiec\'),
            (\'Świdwin\'),
            (\'Przasnysz\'),
            (\'Żagań\'),
            (\'Piaseczno\'),
            (\'Wysokie Mazowieckie\'),
            (\'Leżajsk\'),
            (\'Zawiercie\'),
            (\'Kędzierzyn-Koźle\'),
            (\'Bieruń\'),
            (\'Myszków\'),
            (\'Słupsk\'),
            (\'Węgrów\'),
            (\'Wadowice\'),
            (\'Olkusz\'),
            (\'Sucha Beskidzka\'),
            (\'Ożarów Mazowiecki\'),
            (\'Pszczyna\'),
            (\'Myślenice\'),
            (\'Lubliniec\'),
            (\'Wieluń\'),
            (\'Wyszków\'),
            (\'Rawicz\'),
            (\'Września\'),
            (\'Śrem\'),
            (\'Kępno\'),
            (\'Ropczyce\'),
            (\'Dąbrowa Tarnowska\'),
            (\'Polkowice\'),
            (\'Kartuzy\'),
            (\'Szamotuły\'),
            (\'Proszowice\'),
            (\'Kłobuck\'),
            (\'Nisko\'),
            (\'Ząbkowice Śląskie\'),
            (\'Strzelce Opolskie\'),
            (\'Strzyżów\'),
            (\'Środa Wielkopolska\'),
            (\'Wieruszów\'),
            (\'Końskie\'),
            (\'Busko-Zdrój\'),
            (\'Nowy Tomyśl\'),
            (\'Białobrzegi\'),
            (\'Miechów\'),
            (\'Ryki\'),
            (\'Ostrzeszów\'),
            (\'Strzelin\'),
            (\'Szydłowiec\'),
            (\'Staszów\'),
            (\'Żuromin\'),
            (\'Opatów\'),
            (\'Sztum\'),
            (\'Słubice\'),
            (\'Lesko\'),
            (\'Żnin\'),
            (\'Pajęczno\'),
            (\'Parczew\'),
            (\'Mogilno\'),
            (\'Pińczów\'),
            (\'Pyrzyce\'),
            (\'Mońki\'),
            (\'Środa Śląska\'),
            (\'Opole Lubelskie\'),
            (\'Łosice\'),
            (\'Zwoleń\'),
            (\'Namysłów\'),
            (\'Nowy Dwór Gdański\'),
            (\'Tuchola\'),
            (\'Lipsko\'),
            (\'Sokółka\'),
            (\'Włoszczowa\'),
            (\'Olesno\'),
            (\'Sępólno Krajeńskie\'),
            (\'Poddębice\'),
            (\'Przysucha\'),
            (\'Wołów\'),
            (\'Myślibórz\'),
            (\'Łobez\'),
            (\'Milicz\'),
            (\'Strzelce Krajeńskie\'),
            (\'Pisz\'),
            (\'Sulęcin\'),
            (\'Ustrzyki Dolne\'),
            (\'Międzychód\');
        ');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE city');
    }
}
