doctrine_migrations:
    migrations_paths:
        'App\Migrations': '%kernel.project_dir%/migrations'
    enable_profiler: false
    services:
        'Doctrine\Migrations\Version\MigrationFactory': 'App\Migrations\Factory\MigrationFactory'
